name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ap-southeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Make deploy script executable
        run: chmod +x ./deployment/deploy.sh

      - name: Deploy to dev environment
        run: bash ./deployment/deploy.sh dev